services:
  nginx:
    restart:        always
    build:
      context:      requirements/nginx/
      dockerfile:   Dockerfile
    container_name: nginx
    env_file:       .env
    ports:
      - 443:443
  
  mariadb:
    restart:        always
    build:
      context:      requirements/mariadb/
      dockerfile:   Dockerfile
    container_name: mariadb
    env_file:       .env
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql/

volumes:
  database:
    driver:       local
    driver_opts: 
      device:     /home/${LOGNAME}/data/database/
      type:       none
      o:          bind