services:
  mariadb:
    restart:        always
    build:
      context:      requirements/mariadb/
      dockerfile:   Dockerfile
    container_name: mariadb
    env_file:       .env
    volumes:
      - db:/var/lib/mysql/
    networks: 
      - inception

  wordpress:
    restart:        always  
    build:
      context:      requirements/wordpress/  
      dockerfile:   Dockerfile
    container_name: wordpress
    env_file:       .env
    volumes:
      - wp:/usr/share/webapps/
    depends_on:
      - mariadb
    networks: 
      - inception

  nginx:
    restart:        always  
    build:
      context:      requirements/nginx/  
      dockerfile:   Dockerfile
    container_name: nginx
    env_file:       .env
    ports:
      - 443:443  
    networks: 
      - inception
  
volumes:
  db:
    driver:       local
    driver_opts: 
      device:     /home/${LOGNAME}/data/db
      type:       none
      o:          bind

  wp:
    driver:       local
    driver_opts: 
      device:     /home/${LOGNAME}/data/wp
      type:       none
      o:          bind

networks:
  inception:
    driver: bridge