services:
  nginx:
    restart:        always
    build:
      context:      requirements/nginx/
      dockerfile:   Dockerfile
    container_name: nginx
    env_file:       .env
    ports:
      - 443:443
  
  mariadb:
    restart:        always
    build:
      context:      requirements/mariadb/
      dockerfile:   Dockerfile
    container_name: mariadb
    env_file:       .env

volumes:
  database:
    driver: local-persist
    driver-opts: /home/${LOGNAME}/data