CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};

DROP USER '${MARIADB_USER}'@'%';
CREATE USER '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_USER_PASSWORD}';

DROP USER 'hypervisor'@'%';
CREATE USER 'hypervisor'@'%' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';

GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_USER_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO 'hypervisor'@'%' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';
FLUSH PRIVILEGES;

USE ${DATABASE_NAME}
