CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME} CHARACTER SET utf8;

CREATE USER IF NOT EXISTS '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_USER_PASSWORD}';
CREATE USER IF NOT EXISTS 'hypervisor'@'%' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}';

GRANT ALL ON ${DATABASE_NAME}.* TO '${MARIADB_USER}'@'%';
GRANT ALL ON *.* TO 'hypervisor'@'%';

FLUSH PRIVILEGES;
