CREATE DATABASE IF NOT EXISTS ${DATABASE_NAME};
CREATE USER 'hypervisor'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_USER_PASSWORD}';
GRANT ALL PRIVILEGES ON ${DATABASE_NAME}.* TO 'hypervisor'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
FLUSH PRIVILEGES;